pipeline {
    agent any

    stages {
        stage('Checkout Repo') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Application') {
            steps {
                sh '''
                  docker compose pull
                  docker compose up -d
                '''
            }
        }
    }
}
